# Общие параметры данных
data:
  field_separator: "\t"
  seq_separator: " "
  USER_ID_FIELD: user_id
  ITEM_ID_FIELD: item_id
  TIME_FIELD: timestamp
  RATING_FIELD: rating

MAX_ITEM_LIST_LENGTH: 50
ITEM_LIST_LENGTH_FIELD: 'item_length'
LIST_SUFFIX: '_list'
max_seq_length: 50

load_col:
  inter: [user_id, item_id, rating, timestamp]

  # Добавляем секцию для работы с признаками
  feature_config:
    use_numerical: true
    use_categorical: true
    numerical_features: []  # Будет заполнено из feature_config
    token_features: []  # Будет заполнено из feature_config
    text_fields: []  # Будет заполнено из feature_config

# Параметры для последовательных моделей
train_neg_sample_args: ~
neg_sampling: ~

# Параметры для обучения
epochs: 1
learning_rate: 0.001
train_batch_size: 2048
eval_batch_size: 2048
stopping_step: 10
loss_type: 'CE'
weight_decay: 0.0

# Параметры оценки
metrics: ["Hit", "MRR", "NDCG", "Precision", "Recall"]
valid_metric: NDCG@10
topk: [5, 10, 20]
eval_args:
  split: {'RS': [0.8, 0.1, 0.1]}
  order: 'TO'
  group_by: 'user'
  mode: full

# Параметры для оптимизации памяти
buffer_size: 10000
pin_memory: true
prefetch_factor: 2

# Параметры логирования
log_wandb: true
wandb_project: "recom_text_compares"
save_dataset: true
save_checkpoint: true
log_interval: 100
