model:
  text_model_name: "intfloat/multilingual-e5-base"
  id_embed_dim: 256
  text_embed_dim: 768

data:
  max_length: 128
  batch_size: 256

training:
  epochs: 2
  learning_rate: 3e-5
  lambda_rec: 0.5
  weight_decay: 0.01
  contrastive_loss: "cos_emb" # cos_emb, ...
  validation_size: 0.1
  random_seed: 42
  checkpoint_dir: "checkpoints"  # Базовая директория для чекпоинтов
  save_strategy: "epoch"         # Когда сохранять: "epoch" или "best"
  save_steps: 1                  # Сохранять каждые N эпох
  save_total_limit: 3           # Максимальное количество сохраняемых чекпоинтов 

metrics:
  sim_threshold_precision: null  # Будет вычислено автоматически
  sim_threshold_ndcg: null       # Будет вычислено автоматически
  calibration_samples: 1000      # Количество образцов для калибровки
  
inference:
  embeddings_path: "./data/item_embeddings.npy" 
  index_path: "./data/video_index.faiss"      
  ids_path: "./data/video_ids.npy"        
  model_path: "intfloat/multilingual-e5-large"  # Путь к директории с моделью
  num_examples: 5  # Количество примеров для показа
  top_k: 10       # Количество рекомендаций для каждого пользователя